Avoid setting explName to true if name is null in POJOPropertyBuilder
This change enables backwards compatibility of Jackson 2.4.0 with
modules relying on the 2.3 API (e.g., jackson-module-scala 2.3.X).

Prior to this change, old versions of jackson-module-scala would
receive this exception, when running with Jacskon 2.4:
```
java.lang.IllegalArgumentException: Can not pass true for 'explName' if name is null/empty
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder$Linked.<init>(POJOPropertyBuilder.java:955)
```

Note that this behavior is effectively what jackson-module-scala does in 2.4.0:
https://github.com/FasterXML/jackson-module-scala/blob/master/src/main/scala/com/fasterxml/jackson/module/scala/introspect/ScalaPropertiesCollector.scala#L211